name: build and test on pull

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Build with dotnet
      run: dotnet build --configuration Release

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Run Unit Tests
      run: |
        docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome 
        dotnet test --verbosity normal --configuration Release
      
  automerge:
    needs: [build, test]
    
    runs-on: ubuntu-latest
    steps:
      - name: get user name
        run: echo "${{github.actor}}"
      - name: automerge
        uses: "pascalgn/automerge-action@ccae530ae13b6af67a7a2009c266fe925844e658"
        if: github.actor == 'dependabot-preview[bot]'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
 
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.0.0
        if: github.actor == 'dependabot-preview[bot]' && success()
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: push-event
