//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxeAccessibilityDriver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxeAccessibilityDriver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CHECKLIST_DATE_CELL {
            get {
                return ResourceManager.GetString("CHECKLIST_DATE_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CHECKLIST_DATE_ROW {
            get {
                return ResourceManager.GetString("CHECKLIST_DATE_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CHECKLIST_START_COL {
            get {
                return ResourceManager.GetString("CHECKLIST_START_COL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CHECKLIST_TOTAL_CELL {
            get {
                return ResourceManager.GetString("CHECKLIST_TOTAL_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62.
        /// </summary>
        internal static string CHECKLIST_TOTAL_ROW {
            get {
                return ResourceManager.GetString("CHECKLIST_TOTAL_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CommentColumn {
            get {
                return ResourceManager.GetString("CommentColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string CriteriaColumn {
            get {
                return ResourceManager.GetString("CriteriaColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string CriteriaFail {
            get {
                return ResourceManager.GetString("CriteriaFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete.
        /// </summary>
        internal static string CriteriaIncomplete {
            get {
                return ResourceManager.GetString("CriteriaIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria not applicable.
        /// </summary>
        internal static string CriteriaNA {
            get {
                return ResourceManager.GetString("CriteriaNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Manual Testing.
        /// </summary>
        internal static string CriteriaNeedManual {
            get {
                return ResourceManager.GetString("CriteriaNeedManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string CriteriaPass {
            get {
                return ResourceManager.GetString("CriteriaPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CriteriaNA.
        /// </summary>
        internal static string Inapplicable {
            get {
                return ResourceManager.GetString("Inapplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CriteriaIncomplete.
        /// </summary>
        internal static string Incomplete {
            get {
                return ResourceManager.GetString("Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string ISSUE_HIDDEN_CRITERA_NAME_CELL {
            get {
                return ResourceManager.GetString("ISSUE_HIDDEN_CRITERA_NAME_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string IssueKeycritical {
            get {
                return ResourceManager.GetString("IssueKeycritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string IssueKeymoderate {
            get {
                return ResourceManager.GetString("IssueKeymoderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string IssueKeyserious {
            get {
                return ResourceManager.GetString("IssueKeyserious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CriteriaPass.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCAG 2.0 Compliance Checklist.
        /// </summary>
        internal static string SheetCheckList {
            get {
                return ResourceManager.GetString("SheetCheckList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Tracking Log.
        /// </summary>
        internal static string SheetIssueLog {
            get {
                return ResourceManager.GetString("SheetIssueLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Summary.
        /// </summary>
        internal static string SheetSummary {
            get {
                return ResourceManager.GetString("SheetSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string SUMMARY_DATE_CELL {
            get {
                return ResourceManager.GetString("SUMMARY_DATE_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string SUMMARY_DATE_ROW {
            get {
                return ResourceManager.GetString("SUMMARY_DATE_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string SUMMARY_LINKS {
            get {
                return ResourceManager.GetString("SUMMARY_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string SUMMARY_PROGRESS_CELL {
            get {
                return ResourceManager.GetString("SUMMARY_PROGRESS_CELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string SUMMARY_PROGRESS_ROW {
            get {
                return ResourceManager.GetString("SUMMARY_PROGRESS_ROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string SUMMARY_SUMMARY {
            get {
                return ResourceManager.GetString("SUMMARY_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38.
        /// </summary>
        internal static string TOTAL_CRITERIA {
            get {
                return ResourceManager.GetString("TOTAL_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CriteriaFail.
        /// </summary>
        internal static string Violations {
            get {
                return ResourceManager.GetString("Violations", resourceCulture);
            }
        }
    }
}
